[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the redirects section as it's not needed with the Next.js plugin
# The plugin handles routing automatically 